### ISSUE TITLE
Blocks ALL pages on a site!

### ISSUE THREAD

**Issue by glen777** [f30d0r/url-corrector#2]
Unfortunately, this blocks ALL pages on a website, except the homepage!   Nice idea, but useless in its current state.   Using GetSimple version 3.3.11.  
Simple urls like http://somesite.com terkidanemhret.org/page3/  won't work at all, despite the correct setting of fancy url:  %parent%/%slug%/

**Comment by frusanov** [comment]
Hi! Please tell, do you use any other plugins with url-corretor? And what version of PHP are you use?

**Comment by glen777** [comment]
Thanks for the response.
The version is PHP 7.1 
(If I recall correctly, I I tried the URLcorrector plugin with all other plugins Disabled, as I do whenever encountering problems.  But that was weeks ago, and I no longer have the URLcorrector. )
My 12 other Plugins are:
I18N Base	
I18N Gallery	
'I18N Multilevel navigation & breadcrumbs'; 
I18N Search
Imagizer
Modern Admin	
p01-contact	
Pages excerpts	
Responsive FileManager
Theme Highlighter
Theme Settings	
'Multi User'

**Comment by glen777** [comment]
Update: I was using PHP 7.2 on that site (I just checked).  I still have the URLcorrector there, but it is disabled, as the site won't work with it.)

**Comment by glen777** [comment]
Also, it's a VPS server, setup on Vultr.com using Serverpilot

**Comment by frusanov** [comment]
Plugin had a compatibility problem with PHP 7. I refract code, now it works on PHP 7. You can download new version [here](https://github.com/f30d0r/url-corrector/releases)

**Comment by glen777** [comment]
Ok, I finally got around to testing it, and all works great now! Thanks so much.   This is really an important plugin.  I just now gave it a 5-star rating on the getsimpleCMS site.
